name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: setup dependence
      run: ./setup.sh
    - name: make
      run: cmake . && make 
 
